language: rust
rust:
- beta
- stable
- nightly

script:
- cargo fmt --all -- --write-mode=diff
- cargo build --all --all-features
- cargo test --all --all-features

notifications:
  email:
    on_success: never
